#!/bin/bash
#cd进脚本的目录
realpath="$(dirname "$(readlink -f "$0")")"
cd "${realpath}" || die 1 "无法cd到${realpath}"

#shellcheck source=common
source common

#创建PID锁
createpid

#处理SIGTERM
trap handle_term SIGTERM
trap handle_term SIGINT

function handle_term()
{
    printf "\n"

    log "检测到SIGTERM，正在退出..."
    exit_gracefully
}

function exit_gracefully()
{
    log "再见！"

    #移除URL文件
    rm "${TARGETFILE}"    

    #移除PID锁
    removepid
    
    #退出
    exit 0
}

function clear_urlfile()
{
    true > "${TARGETFILE}"
}

function main()
{
    #检查URL是否存在
    if [ -f "${TARGETFILE}" ];then
        #只获取4KB大小的内容，一般也不会有URL长到超过4KB吧...
        content="$(head -c 4K "${TARGETFILE}")"

        if [ -n "${content}" ];then
            log "从文件获取到内容：${content}";

            #如果内容是die(结束脚本)
            if [ "${content}" == "${ENDCONTENT}" ];then
                exit_gracefully
            fi

            if [[ "${content}" == "http://"* ]] || [[  "${content}" == "https://"* ]];then
                #打开URL
                "${OPENCOMMAND}" "${content}" 2>&1 | log &
            else
                log "获取的内容不是HTTP网址"
            fi;

            #清空URL文件
            clear_urlfile

            #清空target变量
            unset content
        fi;

        unset content
    else
        log "文件${TARGETFILE}不存在，将尝试重新创建..."
        clear_urlfile || die "${RET_URLFILE_FAILED}" "无法创建URL文件${TARGETFILE}"
    fi;
}

#创建或清空URL文件
clear_urlfile || true
log "开始监测URL..."

#inotify

if [ -z "${INOTIFY}" ];then
    readonly INOTIFY="inotifywait"
fi;

if [ "${USEINOTIFY}" == "1" ];then
    log "将使用${INOTIFY}作为inotify..."
    if ! which "${INOTIFY}" > /dev/null;then
        die "${RET_DEPENDENCY_MISSING}" "缺少依赖：inotifywait"
    fi

    if [ ! "$(${INOTIFY} --help | head -n1 | cut -d ' ' -f1)" == "inotifywait" ];then
        die "${RET_DEPENDENCY_MISSING}" "无法确定${INOTIFY}是有效的inotifywait"
    fi
fi

log "警告：日志中输出的内容可能会包含您帐号的相关信息，请在分享出去前先检查一遍！"

while true; do
    if [ "${USEINOTIFY}" == "1" ];then
        while "${INOTIFY}" -e close_write -e delete_self "${TARGETFILE}" > /dev/null 2>/dev/null;do
            main
        done
    else
        main;

        #暂停0.2秒
        sleep 0.2;
    fi;
done