#!/bin/bash
#shellcheck source=common
source "$(dirname "$(readlink -f "$0")")/common"

#移除NVIDIA Offload环境变量
#避免Chrome无法激活硬件加速
unset __GLX_VENDOR_LIBRARY_NAME
unset __NV_PRIME_RENDER_OFFLOAD
unset MESA_VK_DEVICE_SELECT

./browserfix & disown