#!/bin/bash
#cd进脚本的目录
source "$(dirname "$(readlink -f "$0")")/../scripts/common/common"

for rd in "$(dirname "$(readlink -f "$0")")"/*;do
    if [ -d "$rd" ];then
        #log "D: $rd"
        d="$rd"

        for f in "$d"/start*;do
            if [ "$f" == "$d/start*" ];then
                #log "SKIP:$f"
                continue
            fi

            #log "F: $f"
            log "正在启动$f"
            "$f" & disown;
        done;
    fi;
done;