#!/bin/bash
DISPLAYNAME="DeviceLost检测器"

#shellcheck source=common
source "$(dirname "$(readlink -f "$0")")/common"

#USEINOTIFY=1

createpid
checkinotify

function handle_term()
{
    log "再见！"

    removepid
    exit 0
}

function main()
{
    tailOpt="$(tail -n1 "${TARGETFILE}")"

    if [ -n "${tailOpt}" ];then
        log "捕获到 ${tailOpt}"

        #DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
        if echo "${tailOpt}" | grep "VK_ERROR_DEVICE_LOST" -q;then
            zenity --info --text "原神(${EXEBASENAME}.exe)因 ${tailOpt} 崩溃，正在退出..."&
            killall "${EXEBASENAME}".exe >/dev/null 2>/dev/null || true #die "${RET_GENERIC_FAILED}" "没有找到进程"
        fi;

        if [ "${tailOpt}" == "$ENDCONTENT" ];then
            sed "s/${ENDCONTENT}//g" -i "${TARGETFILE}"
            handle_term
        fi

    fi;

    unset tailOpt
}

log "开始监测${TARGETFILE}"

while true; do
    if [ ! -f "${TARGETFILE}" ];then
        log "没有找到目标日志：${TARGETFILE}，正在创建..."
        touch "${TARGETFILE}"
    fi;

    if [ "${USEINOTIFY}" == "1" ];then
        while "${INOTIFY}" -e close_write "${TARGETFILE}" >/dev/null 2>/dev/null;do
            main
        done
    else
        main
    
        sleep 0.2;
    fi
done