#!/bin/bash
DISPLAYNAME="DeviceLost检测器"

#shellcheck source=common
source "$(dirname "$(readlink -f "$0")")/common"

#USEINOTIFY=1

createpid
checkinotify

function on_term()
{
    removepid
}

function main()
{
    #只获取1KB的内容，一般也不会有d3d日志能一行刷1K以上吧...
    tailOpt="$(tail -c 1K -n1 "${TARGETFILE}")"

    if [ -n "${tailOpt}" ];then
        log "捕获到 ${tailOpt}"

        #DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
        if echo "${tailOpt}" | grep "VK_ERROR_DEVICE_LOST" -q;then
            zenity --info --text "原神(${EXEBASENAME}.exe)因 ${tailOpt} 崩溃，正在退出..."&
            killall "${EXEBASENAME}".exe >/dev/null 2>/dev/null || true #die "${RET_GENERIC_FAILED}" "没有找到进程"
        fi;

        if [ "${tailOpt}" == "$ENDCONTENT" ];then
            sed "s/${ENDCONTENT}//g" -i "${TARGETFILE}"
            handle_term
        fi

    fi;

    unset tailOpt
}

#文件里可能有WDLEND,事先替换
sed "s/${ENDCONTENT}//g" -i "${TARGETFILE}"

log "开始监测${TARGETFILE}"

while true; do
    if [ ! -f "${TARGETFILE}" ];then
        log LWARN "没有找到目标日志：${TARGETFILE}，正在创建..."
        touch "${TARGETFILE}"
    fi;

    if [ "${USEINOTIFY}" == "1" ];then
        while "${INOTIFY}" -e modify "${TARGETFILE}" >/dev/null 2>/dev/null;do
            main
        done
    else
        main
    
        sleep 0.2;
    fi
done